### ISSUE TITLE
Pattern (Regex) does not work

### ISSUE THREAD

**Issue by ManuelRosenthaler** [OMAS-IIIF/oldaplib#26]
When u use ```^[\w\.-]+@[a-zA-Z\d-]+(\.[a-zA-Z\d-]+)*\.[a-zA-Z]{2,}$```as Pattern, i recieve the error: ```GraphDB Transaction update failed. Reason: "Transaction handling error: Lexical error at line 37, column 28.  Encountered: \'119\' (119), after prefix "\\"^[\\\\""```

**Comment by lrosenth** [comment]
Escaping of string was not setup correctly in the Xsd_string class. With the bugfix there, regex patterns are written correctly (regarding RDF) to the triple store
