### ISSUE TITLE
In RDF, Name and description seem to be mandatory -- which should not be 

### ISSUE THREAD

**Issue by ManuelRosenthaler** [OMAS-IIIF/oldaplib#27]
the minimum fields to create a standalone property are

1. iri
2. datatype/class
3. description
4. name

If you try to create a standalone property with only an iri and e.g. datatype u get the following error message:
```
GraphDB Transaction update failed. Reason: "Transaction handling error: Expected an RDF value here, found \';\' [line 16]"
```
This error accurs if you dont have either the name or the description but does *not* accure when you have both present

**Comment by lrosenth** [comment]
Works
